Add syntax highlighting to the blog
frontity/frontity.org pull request #143
Opened 2020-10-03 19:20 UTC by michalczaplinski

**What**

Add the syntax highlighting to the twentytwenty theme which is used for the frontity blog.

**How**

Add a custom download of `prism.js` & styles necessary for syntax highlight.

**Notes** 

The content editors can now add one of the custom classes to the blocks in gutenberg:
- `language-css`
- `language-javascript`
- `language-html`
- `language-jsx` (recommended if the code block includes a react component)
- `language-bash`

If you need to support another language, you will have to re-download the custom bundle of prism.js from https://prismjs.com/download.html and replace [the current one](https://github.com/frontity/frontity.org/blob/9872bce480fba45cc0fecf63a030590e7bc38e97/packages/twentytwenty-theme/src/prism.js).

2020-10-03 19:22 UTC, frontibotito commented
Deploy preview for _website_ ready!

Built with commit 40d1fac100c33e8a13362756b15f6ae7a5650002

https://frontity-org-f062bklkk.vercel.app

2020-10-05 16:37 UTC, luisherranz commented
Is this supposed to be working on posts like this https://frontity-org-49k7sxspr.vercel.app/blog/how-to-create-a-react-theme-in-30-minutes/?

2020-10-05 16:39 UTC, luisherranz requested changes
I think this is working only in SSR, but not CSR. I've tried this post: https://frontity-org-49k7sxspr.vercel.app/blog/how-to-create-a-react-theme-in-30-minutes

@michalczaplinski Could you please take a look? 🙂

Also, is there a possibility to code split the prism.js code so it's only added if the HTML contains a `<code>` block?

2020-10-05 18:55 UTC, michalczaplinski commented
> I think this is working only in SSR, but not CSR. I've tried this post: https://frontity-org-49k7sxspr.vercel.app/blog/how-to-create-a-react-theme-in-30-minutes
> 
> @michalczaplinski Could you please take a look? 🙂

I think you meant that it's only working in CSR and not in SSR :) 

Prism.js on the client works by modifying the DOM (it will grab every `<code>` element that has a `language-***` class and split it into multiple span elements).

On the server, frontity would have to access the html markup that is generated by the react SSR and modify it before returning it to the client and we don't have such a hook at the moment. So something like: 

```js
let html = ReactDOMServer.renderToString(jsx);
html = Prism.highlightAllUnder(html);
```

> Also, is there a possibility to code split the prism.js code so it's only added if the HTML contains a `<code>` block? Maybe we could create a Prism processor that has code-splitting and people can reuse in their blogs.

I guess the only solution for now is to write a processor that handles the highlighting for the individual `<code>` elements and it should also handle the code splitting.

2020-10-05 22:37 UTC, michalczaplinski commented on packages/twentytwenty-theme/src/prism-processor.js
> +        `An incorrect "${result[0]}" CSS class has been specified on the <code> element
I've just tested it manually. If you add a fake class to a code block in wordpress like `language-bazinga`, it will trigger this warning

2020-10-05 23:00 UTC, michalczaplinski commented
@luisherranz I've added a processor so that the highlighting now works on both server and client.

However, I could not get the code splitting to work. I think it's not really possible because the processor has to be synchronous so I cannot await a dynamic import inside of the processor.

2020-10-06 08:05 UTC, luisherranz requested changes
> However, I could not get the code splitting to work. I think it's not really possible because the processor has to be synchronous so I cannot await a dynamic import inside of the processor.

We are using [loadable](https://github.com/gregberge/loadable-components) for code-splitting, so the code has to be behind of a React component.

2020-10-06 14:53 UTC, luisherranz commented
> I think you meant that it's only working in CSR and not in SSR :)

I actually meant that it was working on the first CSR but not on subsequent CSRs. Sorry about that.

It's really cool that now it works in SSR as well though 🙂

2020-10-06 23:11 UTC, michalczaplinski commented
> > I think you meant that it's only working in CSR and not in SSR :)
> 
> I actually meant that it was working on the first CSR but not on subsequent CSRs. Sorry about that.
> 
> It's really cool that now it works in SSR as well though 🙂

Right, I see :)

2020-10-07 06:58 UTC, luisherranz approved these changes
Thanks Michal!!

I think this processor is really cool, so I opened a community thread to talk about how we can share this type of processor: https://community.frontity.org/t/how-to-share-gutenberg-processors/3069

2020-10-07 15:08 UTC, merged